apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-ng
  template:
    metadata:
      labels:
        app: stress-ng
    spec:
      containers:
        - name: stress-ng
          imagePullPolicy: Never
          image: stress-ng-service
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: stress-ng-service
spec:
  type: NodePort
  selector:
    app: stress-ng
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31190
